const qBank = [
  {id:1,
    question: "A knish is traditionally stuffed with what filling?",
    options:{"A": "potato",
    "B": "creamed corn",
    "C": "lemon custard",
    "D": "raspberry jelly"},
    answer: "A"
  }, {id:2,
    question: "A pita is a type of what?",
    options:{"A": "fresh fruit",
    "B": "flat bread",
    "C": "French tart",
    "D": "friend bean dip"},
    answer: "B"
  }, {id:3,
    question: "A second-year college student is usually called a what?",
    options:{"A": "sophomore",
    "B": "senior",
    "C": "freshman ",
    "D": "junior "},
    answer: "A"
  }, {id:4,
    question: "A student who earns a J.D. can begin his or her career as a what?",
    options:{"A": "lawyer",
    "B": "bricklayer",
    "C": "doctor",
    "D": "accountant"},
    answer: "A"
  }, {id:5,
    question: "A triptych is a work of art that is painted on how many panels?",
    options:{"A": "two",
    "B": "three",
    "C": "five",
    "D": "eight"},
    answer: "B"
  },{id:6,
    question: "A flashing red traffic light signifies that a driver should do what?",
    options:{"A": "stop",
    "B": "speed up",
    "C": "proceed with caution",
    "D": "honk the horn"},
    answer: "A"
  }, {id:7,
    question: "A knish is traditionally stuffed with what filling?",
    options:{"A": "potato",
    "B": "creamed corn",
    "C": "lemon custard",
    "D": "raspberry jelly"},
    answer: "A"
  }, {id:8,
    question: "A pita is a type of what?",
    options:{"A": "fresh fruit",
    "B": "flat bread",
    "C": "French tart",
    "D": "friend bean dip"},
    answer: "B"
  }, {id:9,
    question: "A portrait that comically exaggerates a person's physical traits is called a what?",
    options:{"A": "landscape",
    "B": "caricature",
    "C": "still life",
    "D": "Impressionism"},
    answer: "B"
  }, {id:10,
    question: "A second-year college student is usually called a what?",
    options:{"A": "sophomore",
    "B": "senior",
    "C": "freshman ",
    "D": "junior "},
    answer: "A"
  },{id:11,
    question: "According to folklore, the 'jackalope' is an antlered version of what animal?",
    options:{"A": "chicken",
    "B": "rabbit",
    "C": "moose",
    "D": "snake"},
    answer: "B"
  }, {id:12,
    question: "According to Greek mythology, who was Apollo's twin sister?",
    options:{"A": "Aphrodite",
    "B": "Artemis",
    "C": "Venus",
    "D": "Athena"},
    answer: "B"
  }, {id:13,
    question: "According to legend, if you give someone the 'evil eye' what are you doing?",
    options:{"A": "cursing them",
    "B": "blessing a child",
    "C": "counting money",
    "D": "passing time"},
    answer: "A"
  }, {id:14,
    question: "According to legend, in what country are you most likely to meet a leprechaun?",
    options:{"A": "Ireland",
    "B": "Poland",
    "C": "Greenland",
    "D": "Scotland"},
    answer: "A"
  }, {id:15,
    question: "According to the American Kennel Club, what is the most popular breed of dog in the US as of 1999?",
    options:{"A": "Poodle",
    "B": "Beagle",
    "C": "German shepherd",
    "D": "Labrador retriever"},
    answer: "D"
  }, {id:16,
    question: "A student who earns a J.D. can begin his or her career as a what?",
    options:{"A": "lawyer",
    "B": "bricklayer",
    "C": "doctor",
    "D": "accountant"},
    answer: "A"
  }, {id:17,
    question: "A triptych is a work of art that is painted on how many panels?",
    options:{"A": "two",
    "B": "three",
    "C": "five",
    "D": "eight"},
    answer: "B"
  }, {id:18,
    question: "According to a famous line from the existentialist play 'No Exit' what is hell?",
    options:{"A": "oneself",
    "B": "other people",
    "C": "little made large",
    "D": "hued in green and blue"},
    answer: "B"
  }, {id:19,
    question: "According to a popular slogan, what state should people not 'mess with'?",
    options:{"A": "New York",
    "B": "Texas",
    "C": "Montana",
    "D": "Rhode Island"},
    answer: "B"
  }, {id:20,
    question: "According to a Yale University study, what smell is the most recognizable to American adults?",
    options:{"A": "tuna",
    "B": "laundry",
    "C": "popcorn",
    "D": "coffee"},
    answer: "D"
  },{id:21,
      question: "As of 1999, which state has the most Girl Scouts?",
      options:{"A": "California",
      "B": "Illinois",
      "C": "New York",
      "D": "Pennsylvania"},
      answer: "A"
    }, {id:22,
      question: "Astronaut John Glenn served as a pilot in what branch of the military?",
      options:{"A": "Army",
      "B": "Air Force",
      "C": "Marines",
      "D": "Navy"},
      answer: "C"
    }, {id:23,
      question: "At the equator, how fast is the earth's surface turning?",
      options:{"A": "about 100 miles per hour",
      "B": "about 500 miles per hour",
      "C": "about 1000 miles per hour",
      "D": "about 2000 miles per hour"},
      answer: "C"
    }, {id:24,
      question: "At what age can someone first attend an R-rated movie without an accompanying adult?",
      options:{"A": "15",
      "B": "17",
      "C": "18",
      "D": "21"},
      answer: "C"
    }, {id:25,
      question: "Backgammon is a how many player game?",
      options:{"A": "Two",
      "B": "Three",
      "C": "Four",
      "D": "Six"},
      answer: "A"
    },{id:26,
      question: "According to the Bible, Moses and Aaron had a sister named what?",
      options:{"A": "Jochebed",
      "B": "Ruth",
      "C": "Leah",
      "D": "Miriam"},
      answer: "D"
    }, {id:27,
      question: "According to the children's nursery rhyme, what type of ocean did Columbus sail in 1492?",
      options:{"A": "calm",
      "B": "blue",
      "C": "windy",
      "D": "really big"},
      answer: "B"
    }, {id:28,
      question: "According to the Mother Goose nursery rhyme, which child is full of woe?",
      options:{"A": "Monday's child",
      "B": "Wednesday's child",
      "C": "Thursday's child",
      "D": "Saturday's child"},
      answer: "B"
    }, {id:29,
      question: "According to the popular saying, what should you do 'when in Rome'?",
      options:{"A": "watch your wallet",
      "B": "see the Coliseum",
      "C": "as the Romans do",
      "D": "don't drink the water"},
      answer: "C"
    }, {id:30,
      question: "According to the proverb, necessity is the mother of what?",
      options:{"A": "Invention",
      "B": "Luck",
      "C": "Problems",
      "D": "Procrastination"},
      answer: "A"
    }, {id:31,
      question: "According to the title of a popular children's TV show, what color is Bear's big house?",
      options:{"A": "red",
      "B": "green",
      "C": "purple",
      "D": "blue"},
      answer: "D"
    }, {id:32,
      question: "According to the USDA, which food group should you eat the most servings of per day?",
      options:{"A": "vegetables",
      "B": "dairy",
      "C": "meats",
      "D": "breads"},
      answer: "D"
    }, {id:33,
      question: "Ada Lovelace is credited with being the first person to have made what?",
      options:{"A": "a computer program",
      "B": "a souffle",
      "C": "a brassiere",
      "D": "a mystery novel"},
      answer: "A"
    }, {id:34,
      question: "After Prince Charles, who is next in line to be the king of England?",
      options:{"A": "Prince William",
      "B": "Prince Andrew",
      "C": "Prince Edward",
      "D": "Fresh Prince"},
      answer: "A"
    },{id:35,
      question: "An airplane's black box is usually what color?",
      options:{"A": "black",
      "B": "white",
      "C": "orange",
      "D": "purple"},
      answer: "C"
      },{id:36,
        question: "Before he went into coaching, Phil Jackson played for which of the following NBA teams?",
        options:{"A": "Boston Celtics",
        "B": "Los Angeles Lakers",
        "C": "New York Knicks",
        "D": "Philadelphia 76ers"},
        answer: "C"
      }, {id:37,
        question: "By what name is Bob Keeshan better known?",
        options:{"A": "Bozo the Clown",
        "B": "Pee Wee Herman",
        "C": "Captain Kangaroo",
        "D": "Buffalo Bob"},
        answer: "C"
      }, {id:38,
        question: "By what collective name do Christians refer to God the Father, God the Son and the Holy Ghost?",
        options:{"A": "the Trio",
        "B": "the Troika",
        "C": "the Triumvirate",
        "D": "the Trinity"},
        answer: "D"
      }, {id:39,
        question: "By what nickname is the Federal National Mortgage Association known?",
        options:{"A": "Morty",
        "B": "FEMA",
        "C": "Freddie Mac",
        "D": "Fannie Mae"},
        answer: "D"
      }, {id:40,
        question: "Cheddar cheese got its name from a village in what country?",
        options:{"A": "England",
        "B": "France",
        "C": "Switzerland",
        "D": "Denmark"},
        answer: "A"
      }, {id:41,
        question: "Cheese is a necessary ingredient in which of these dishes?",
        options:{"A": "sushi",
        "B": "french fries",
        "C": "veal parmigiano",
        "D": "chicken pot pie"},
        answer: "C"
      }, {id:42,
        question: "During what war did Francis Scott Key write the words to 'The Star-Spangled Banner'?",
        options:{"A": "American Revolution",
        "B": "War of 1812",
        "C": "Civil War",
        "D": "World War I"},
        answer: "B"
      }, {id:43,
        question: "During which war did US troops fight the Battle of New Orleans?",
        options:{"A": "American Revolution",
        "B": "Civil War",
        "C": "Mexican War",
        "D": "War of 1812"},
        answer: "D"
      }, {id:44,
        question: "Each year in pro baseball, the player voted as the best fielder at his position wins what?",
        options:{"A": "a brand new car",
        "B": "the Gold Glove",
        "C": "the Silver Bat",
        "D": "the Brass Baseball"},
        answer: "B"
      }, {id:45,
        question: "Elephant tusks are made of what material?",
        options:{"A": "coral",
        "B": "ivory",
        "C": "bone",
        "D": "calcium"},
        answer: "B"
      },
      
]

 
export default qBank;

 
